### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by ZAZmaster** [cli-ish/bbb-video-converter#1]
Hello, some recorings does not converted with error:
```
# docker run -v /mnt/scalelite-recordings/var/bigbluebutton/published/presentation/e16dd371710acce71110d2315120a819f3de818f-1166245343158:/recdir bbb-converter -i /recdir -o video.mp4 -t 6
2022/10/26 03:23:13 Starting the conversion
2022/10/26 03:23:13 ========================================================
2022/10/26 03:23:13 Recording:  /recdir
2022/10/26 03:23:13 Output:     /recdir/video.mp4
2022/10/26 03:23:13 ========================================================
panic: runtime error: index out of range [0] with length 0

goroutine 33 [running]:
bbb-video-converter/converter/modules/presentation.renderFrames({0x93a350?, 0xc000020600}, {{0x7ffd5faaaf50, 0x7}, {0xc0001701c8, 0x11}, {0xc000162180, 0x1e}, {0x7ffd5faaaf68, 0x1}}, ...)
        /srv/bbb-convert/converter/modules/presentation/browserinteraction.go:106 +0x4bf
bbb-video-converter/converter/modules/presentation.captureFrames({{0x7ffd5faaaf50, 0x7}, {0xc0001701c8, 0x11}, {0xc000162180, 0x1e}, {0x7ffd5faaaf68, 0x1}}, {0xc0003181b0?, 0x0?, ...})
        /srv/bbb-convert/converter/modules/presentation/browserinteraction.go:69 +0xafe
bbb-video-converter/converter/modules/presentation.renderSlides({{0x7ffd5faaaf50, 0x7}, {0xc0001701c8, 0x11}, {0xc000162180, 0x1e}, {0x7ffd5faaaf68, 0x1}}, 0xa41?)
        /srv/bbb-convert/converter/modules/presentation/slides.go:49 +0x15d
bbb-video-converter/converter/modules/presentation.CreatePresentationVideo.func1()
        /srv/bbb-convert/converter/modules/presentation/presentation.go:22 +0x99
created by bbb-video-converter/converter/modules/presentation.CreatePresentationVideo
        /srv/bbb-convert/converter/modules/presentation/presentation.go:20 +0x1b8
```

**Comment by cli-ish** [comment]
Could you share the Recording so i can further test this issue? It seems like the there is a issue with the timestamps.

If the Recording is confidential you could also just upload the shapes.svg, this would help me alot :)

**Comment by ZAZmaster** [comment]
I can't share Recording - its private. With tilmanmoser/bbb-video-download this Recording converted successfully.

**Comment by ZAZmaster** [comment]
Content of shapes.svg
```
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="svgfile" style="position:absolute;height:600px;width:800px" version="1.1" viewBox="0 0 800 600">
  <image id="image1" class="slide" in="0.0" out="7.5" xlink:href="presentation/logo.png" width="1600" height="1200" x="0" y="0" style="visibility:hidden"/>
  <image id="image2" class="slide" in="7.5" out="4314.8" xlink:href="presentation/e16dd371710acce71110d2315120a819f3de818f-1166245343158/slide-1.png" width="1600" height="1131" x="0" y="0" style="visibility:hidden" text="presentation/e16dd371710acce71110d2315120a819f3de818f-1166245343158/textfiles/slide-1.txt"/>
</svg>

```

**Comment by cli-ish** [comment]
Thanks, i will take a look at it as soon as possible.

**Comment by cli-ish** [comment]
Solved in Commit https://github.com/cli-ish/bbb-video-converter/commit/c8b892a12c65593ee0cdca64b48e4bd5d668b057, note that a Docker rebuild is required:

```bash
docker build -t bbb-converter .
```
The error was in the distribution of the work on the given threads. In this case 6 although there is not enough work for this number of threads. Therefore the division resulted in a value below 0 which could not be used.

Now in such a case a rule was introduced which regulates the threads in this case down so that it equals the effort. This may not be performant but solves the problem in this case.

Maybe I have to implement an automatic finding of the best thread number, because with an automated conversion not the perfect thread selection can be made.

**Comment by ZAZmaster** [comment]
Thanks a lot! I'll post the results in a couple of days!

**Comment by ZAZmaster** [comment]
This fix is really helpful!
